# Generated by Django 3.0.3 on 2020-02-12 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Digimon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=250)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              related_name='created_digimons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
