# Generated by Django 3.0.2 on 2020-01-22 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('name', models.CharField(max_length=75)),
                ('effect', models.CharField(max_length=300)),
                ('short_effect', models.CharField(max_length=150)),
                ('api_obj_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=250)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('abilities', models.ManyToManyField(related_name='pokemons', to='pokemon.Ability')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pokemons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
